apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-session
spec:
  serviceName: "user-session"
  replicas: 3
  selector:
    matchLabels:
      app: user-session
  template:
    metadata:
      labels:
        app: user-session
    spec:
      containers:
      - name: user-session
        image: 285982079759.dkr.ecr.us-east-1.amazonaws.com/statefull-repo:latest
        ports:
        - containerPort: 5901
