apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-pod
spec:
  selector:
    matchLabels:
      app: user-pod
  serviceName: "user-pod"
  replicas: 3
  template:
    metadata:
      labels:
        app: user-pod
    spec:
      containers:
        - name: user-pod
          image: 285982079759.dkr.ecr.us-east-1.amazonaws.com/statefull-repo:latest
          ports:
            - containerPort: 8000
